// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWL41hWcR_fvKHO0nMlw1D077Q1GtTMM0',
    appId: '1:785543182480:android:48b6baf9e902e49163c015',
    messagingSenderId: '785543182480',
    projectId: 'doodle-diary',
    storageBucket: 'doodle-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDvzMexuVEZXJNgqOa9B0W4ts-xQQ63yM',
    appId: '1:785543182480:ios:df3918e210b57c6b63c015',
    messagingSenderId: '785543182480',
    projectId: 'doodle-diary',
    storageBucket: 'doodle-diary.appspot.com',
    androidClientId: '785543182480-jufvlumra5pvcdl0drtoo0o01rkqorkd.apps.googleusercontent.com',
    iosClientId: '785543182480-durlla0afdpr32bc81rr482043kl2aiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.canvasVault',
  );

}